version: "3.8"
services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    tty: true
